# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('wager', models.IntegerField()),
                ('betvalue', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('odds', models.IntegerField()),
                ('hometeam', models.CharField(max_length=70)),
                ('awayteam', models.CharField(max_length=70)),
                ('gamedate', models.DateTimeField()),
                ('betpick', models.CharField(max_length=70)),
                ('paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=70)),
                ('awayteam', models.CharField(max_length=70)),
                ('homescore', models.IntegerField()),
                ('awayscore', models.IntegerField()),
                ('gamedate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Game'),
        ),
    ]
