# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-25 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('betting', '0002_auto_20160524_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Better',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=50000.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='gamedate',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
