# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-25 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20160525_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='awayteam',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='hometeam',
        ),
    ]
